"use client";

import { useState, useTransition, type ReactNode } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
} from "@/components/ui/select";
import { createCourseAction } from "@/app/admin/academic/courses/actions";
import { digitsOnly } from "@/lib/admin/form-helpers";
import { Loader2Icon } from "lucide-react";

type AddCourseDialogProps = {
  trigger: ReactNode;
  onSuccess?: () => void;
};

const DEFAULT_FORM = { name: "", completionYear: "3", isSupported: "true" };

export function AddCourseDialog({
  trigger,
  onSuccess,
}: AddCourseDialogProps) {
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState(DEFAULT_FORM);
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  const parsedYear = Number(form.completionYear);
  const formValid =
    form.name.trim() !== "" &&
    Number.isInteger(parsedYear) &&
    parsedYear >= 1 &&
    parsedYear <= 8;

  function resetForm() {
    setForm(DEFAULT_FORM);
    setError(null);
  }

  function handleOpenChange(next: boolean) {
    if (!next) resetForm();
    setOpen(next);
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!formValid || isPending) return;
    setError(null);

    const formData = new FormData();
    formData.set("name", form.name.trim());
    formData.set("completionYear", form.completionYear);
    formData.set("isSupported", form.isSupported);

    startTransition(async () => {
      const res = await createCourseAction(formData);
      if (!res.success) {
        setError(res.error);
        return;
      }

      resetForm();
      onSuccess?.();
      setOpen(false);
    });
  }

  return (
    <>
      <div
        role="button"
        tabIndex={0}
        onClick={() => setOpen(true)}
        onKeyDown={(e) => {
          if (e.key === "Enter" || e.key === " ") setOpen(true);
        }}
        className="inline-flex"
      >
        {trigger}
      </div>

      <Dialog open={open} onOpenChange={handleOpenChange}>
        <DialogContent className="max-w-md">
          <form onSubmit={handleSubmit}>
            <DialogHeader>
              <DialogTitle>Add New Course</DialogTitle>
              <DialogDescription>
                Create a new study program for cadets. The course slug is autogenerated.
              </DialogDescription>
            </DialogHeader>

            <div className="space-y-4 py-4">
              {error && (
                <div className="rounded-md bg-destructive/15 p-3 text-sm text-destructive">
                  {error}
                </div>
              )}

              <Field label="Course Name" required>
                <Input
                  value={form.name}
                  onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))}
                  placeholder="e.g. SAINS KOMPUTER (KEJURUTERAAN PERISIAN)"
                  className="uppercase"
                  disabled={isPending}
                />
              </Field>

              <Field
                label="Completion Duration (Years)"
                required
                description="Standard university duration to graduate (e.g. 3, 4, or 5 years)."
              >
                <Input
                  type="number"
                  min={1}
                  max={8}
                  inputMode="numeric"
                  value={form.completionYear}
                  onChange={(e) =>
                    setForm((f) => ({ ...f, completionYear: digitsOnly(e.target.value) }))
                  }
                  disabled={isPending}
                />
              </Field>

              <Field label="Supported Status">
                <Select
                  value={form.isSupported}
                  onValueChange={(value) => setForm((f) => ({ ...f, isSupported: value }))}
                >
                  <SelectTrigger className="w-full" disabled={isPending}>
                    {form.isSupported === "true" ? "Supported" : "Unsupported"}
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="true">Supported</SelectItem>
                    <SelectItem value="false">Unsupported</SelectItem>
                  </SelectContent>
                </Select>
              </Field>
            </div>

            <DialogFooter>
              <Button type="submit" size="sm" disabled={!formValid || isPending}>
                {isPending && <Loader2Icon className="mr-1.5 size-3.5 animate-spin" />}
                Add Course
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </>
  );
}
